### PR TITLE
Typo AZURE_COSMOSEDB_URI and AZURE_COSMOSEDB_KEY

### PR DESCRIPTION
**Pull request by jkudo**
Typo AZURE_COSMOSEDB_URI and AZURE_COSMOSEDB_KEY

AZURE_COSMOSDB_URI
AZURE_COSMOSDB_KEY

### CODE REVIEW

**Comment by jkudo** [comment]
@microsoft-github-policy-service agree

**Comment by oliverlabs** [comment]
Please note: the code uses the `AZURE_COSMOSEDB_KEY` and `AZURE_COSMOSEDB_URI` names, so it needs to be corrected everywhere.

**Review by dcnsakthi — APPROVED** [review]
Reviewwd Typo issues.

**Comment by akiojin** [comment]
https://aka.ms/anzappazurechatgpt

The configuration created by the above deployment also appears to be AZURE_COSMOSEDB_URI and AZURE_COSMOSEDB_KEY.

**Comment by thivy** [comment]
@jkudo Thank you for looking into this issue. The typo was fixed as part of another PR. 

Looking forward to your future contributions

**Pull request closed without merging**
